version: '3'

services:
  db:
    image: postgres:bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: link-manager-rest-service-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
